name: upi_pay
description: A flutter plugin to launch UPI payment applications on Android and iOS towards making UPI payments.
version: 0.3.0

homepage: https://github.com/drenther/upi_pay

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^1.0.0+1
  universal_io: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.drenther.upi_pay
        pluginClass: UpiPayPlugin
      ios:
        pluginClass: UpiPayPlugin
  assets:
    - assets/apps/ios/
